"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var utilidades_1 = require("./utilidades");
var otro_js_1 = require("./otro.js");
var otro2_js_1 = require("./otro2.js");
console.log(utilidades_1.PI);
console.log(utilidades_1.Sumar(4, 5));
console.log(otro_js_1.saludo);
console.log(utilidades_1.Sumar(10, 5));
console.log(otro2_js_1.saludo2);
